### ISSUE TITLE
Support for async 

### ISSUE THREAD

**Issue by efeker** [f135ta/SimpleProxy#6]
Does this library support async methods?
Thanks

**Comment by stricq** [comment]
Not really, and that's a HUGE detriment to an otherwise excellent project.  There is an open Pull Request that adds async support but it also changes the project from .Net Core to .Net Standard would break me.  When I get some time I'm going to clone this repo and fix that.  I need this for my project at work.

**Comment by f135ta** [comment]
There are plans to implement support for Async. There's also a pull request outstanding - but as @stricq  mentioned - it moves the code to NetStandard which I was REALLY trying to avoid.
